language: objective-c
xcode_workspace: ReactiveTask.xcworkspace
git:
  submodules: false
before_script:
  - git submodule update --init --recursive
script:
  - set -o pipefail && xcodebuild -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" test | xcpretty
matrix:
  include:
    - osx_image: xcode7.3
      xcode_scheme: ReactiveTask
      env: JOB=Xcode7.3
    - osx_image: xcode8
      xcode_scheme: ReactiveTask
      env: JOB=Xcode8
notifications:
  email: false
  slack:
    secure: Nh1mbn1RzYrI5tIY52gNrMy+PX1hdq2rIAJHxJjeiWjQDYfIoynhQ/2NIKs6Y0b0E5GIQEtF1fereyWdxcoEFGloY3cq4HZ7dgqr9kzOHrlDMp80fWbcoTqrgbOsKreFFtrv413d5+YcNkJvkYRfnxbuWLPZPszrcbw82TyRL60=
before_deploy:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage version
  - carthage build --no-skip-current --platform mac
  - carthage archive ReactiveTask
deploy:
  provider: releases
  api_key:
    secure: HL8FyVudN7johEi0hFOVR58NSVB8lFpx4HLzeZZoCz7nabj3LtavDoPF7c72nOYdrV6bhQiLiF2ocsYlfTrAyX5whO3532Lih3mE9NRePRGMyqnVD+4CnJUXusPxbesHq4IkMfEsq40KiqXKBa4XsiHZPhrQhmE+u7I4YIzjOYo=
  file: ReactiveTask.framework.zip
  skip_cleanup: true
  on:
    repo: Carthage/ReactiveTask
    tags: true
    condition: $JOB = Xcode7.3
